# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genetic.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'genetic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgenetic.proto\"t\n\x11IndividualMessage\x12\r\n\x05genes\x18\x01 \x03(\x05\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x05\x12\x11\n\tsender_id\x18\x03 \x01(\x05\x12\x15\n\rlogical_clock\x18\x04 \x01(\x05\x12\x15\n\rphysical_time\x18\x05 \x01(\x01\"\x1f\n\x0cMutexRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"\x1d\n\nMutexReply\x12\x0f\n\x07granted\x18\x01 \x01(\x08\"8\n\x10HeartbeatMessage\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\"\"\n\x0f\x45lectionMessage\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\xeb\x01\n\x0bGeneticNode\x12-\n\x11ReceiveIndividual\x12\x12.IndividualMessage\x1a\x04.Ack\x12\x34\n\x16RequestCriticalSection\x12\r.MutexRequest\x1a\x0b.MutexReply\x12-\n\x16ReleaseCriticalSection\x12\r.MutexRequest\x1a\x04.Ack\x12$\n\tHeartbeat\x12\x11.HeartbeatMessage\x1a\x04.Ack\x12\"\n\x08\x45lection\x12\x10.ElectionMessage\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genetic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDIVIDUALMESSAGE']._serialized_start=17
  _globals['_INDIVIDUALMESSAGE']._serialized_end=133
  _globals['_MUTEXREQUEST']._serialized_start=135
  _globals['_MUTEXREQUEST']._serialized_end=166
  _globals['_MUTEXREPLY']._serialized_start=168
  _globals['_MUTEXREPLY']._serialized_end=197
  _globals['_HEARTBEATMESSAGE']._serialized_start=199
  _globals['_HEARTBEATMESSAGE']._serialized_end=255
  _globals['_ELECTIONMESSAGE']._serialized_start=257
  _globals['_ELECTIONMESSAGE']._serialized_end=291
  _globals['_ACK']._serialized_start=293
  _globals['_ACK']._serialized_end=315
  _globals['_GENETICNODE']._serialized_start=318
  _globals['_GENETICNODE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
