# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import genetic_pb2 as genetic__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in genetic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeneticNodeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveIndividual = channel.unary_unary(
                '/GeneticNode/ReceiveIndividual',
                request_serializer=genetic__pb2.IndividualMessage.SerializeToString,
                response_deserializer=genetic__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestCriticalSection = channel.unary_unary(
                '/GeneticNode/RequestCriticalSection',
                request_serializer=genetic__pb2.MutexRequest.SerializeToString,
                response_deserializer=genetic__pb2.MutexReply.FromString,
                _registered_method=True)
        self.ReleaseCriticalSection = channel.unary_unary(
                '/GeneticNode/ReleaseCriticalSection',
                request_serializer=genetic__pb2.MutexRequest.SerializeToString,
                response_deserializer=genetic__pb2.Ack.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/GeneticNode/Heartbeat',
                request_serializer=genetic__pb2.HeartbeatMessage.SerializeToString,
                response_deserializer=genetic__pb2.Ack.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/GeneticNode/Election',
                request_serializer=genetic__pb2.ElectionMessage.SerializeToString,
                response_deserializer=genetic__pb2.Ack.FromString,
                _registered_method=True)


class GeneticNodeServicer:
    """Missing associated documentation comment in .proto file."""

    def ReceiveIndividual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCriticalSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseCriticalSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneticNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveIndividual,
                    request_deserializer=genetic__pb2.IndividualMessage.FromString,
                    response_serializer=genetic__pb2.Ack.SerializeToString,
            ),
            'RequestCriticalSection': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCriticalSection,
                    request_deserializer=genetic__pb2.MutexRequest.FromString,
                    response_serializer=genetic__pb2.MutexReply.SerializeToString,
            ),
            'ReleaseCriticalSection': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseCriticalSection,
                    request_deserializer=genetic__pb2.MutexRequest.FromString,
                    response_serializer=genetic__pb2.Ack.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=genetic__pb2.HeartbeatMessage.FromString,
                    response_serializer=genetic__pb2.Ack.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=genetic__pb2.ElectionMessage.FromString,
                    response_serializer=genetic__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GeneticNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GeneticNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeneticNode:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GeneticNode/ReceiveIndividual',
            genetic__pb2.IndividualMessage.SerializeToString,
            genetic__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCriticalSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GeneticNode/RequestCriticalSection',
            genetic__pb2.MutexRequest.SerializeToString,
            genetic__pb2.MutexReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseCriticalSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GeneticNode/ReleaseCriticalSection',
            genetic__pb2.MutexRequest.SerializeToString,
            genetic__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GeneticNode/Heartbeat',
            genetic__pb2.HeartbeatMessage.SerializeToString,
            genetic__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GeneticNode/Election',
            genetic__pb2.ElectionMessage.SerializeToString,
            genetic__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
